/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables.records;


import jp.co.toshiba.ppocph.jooq.tables.Chihos;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 地方テーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChihosRecord extends UpdatableRecordImpl<ChihosRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chihos.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chihos.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chihos.name</code>. 地方名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chihos.name</code>. 地方名称
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Chihos.CHIHOS.ID;
    }

    @Override
    public Field<String> field2() {
        return Chihos.CHIHOS.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ChihosRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ChihosRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ChihosRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChihosRecord
     */
    public ChihosRecord() {
        super(Chihos.CHIHOS);
    }

    /**
     * Create a detached, initialised ChihosRecord
     */
    public ChihosRecord(Long id, String name) {
        super(Chihos.CHIHOS);

        setId(id);
        setName(name);
    }
}
