/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables.records;


import jp.co.toshiba.ppocph.jooq.tables.Cities;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 都市テーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CitiesRecord extends UpdatableRecordImpl<CitiesRecord> implements Record7<Long, String, String, Long, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cities.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cities.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cities.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cities.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.cities.pronunciation</code>. 読み方
     */
    public void setPronunciation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cities.pronunciation</code>. 読み方
     */
    public String getPronunciation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.cities.population</code>. 人口数量
     */
    public void setPopulation(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cities.population</code>. 人口数量
     */
    public Long getPopulation() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.cities.city_flag</code>. 都市フラグ
     */
    public void setCityFlag(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cities.city_flag</code>. 都市フラグ
     */
    public String getCityFlag() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cities.district_id</code>. 地域ID
     */
    public void setDistrictId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cities.district_id</code>. 地域ID
     */
    public Long getDistrictId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.cities.delete_flg</code>. 論理削除フラグ
     */
    public void setDeleteFlg(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cities.delete_flg</code>. 論理削除フラグ
     */
    public String getDeleteFlg() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Long, String, Long, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, Long, String, Long, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Cities.CITIES.ID;
    }

    @Override
    public Field<String> field2() {
        return Cities.CITIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Cities.CITIES.PRONUNCIATION;
    }

    @Override
    public Field<Long> field4() {
        return Cities.CITIES.POPULATION;
    }

    @Override
    public Field<String> field5() {
        return Cities.CITIES.CITY_FLAG;
    }

    @Override
    public Field<Long> field6() {
        return Cities.CITIES.DISTRICT_ID;
    }

    @Override
    public Field<String> field7() {
        return Cities.CITIES.DELETE_FLG;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPronunciation();
    }

    @Override
    public Long component4() {
        return getPopulation();
    }

    @Override
    public String component5() {
        return getCityFlag();
    }

    @Override
    public Long component6() {
        return getDistrictId();
    }

    @Override
    public String component7() {
        return getDeleteFlg();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPronunciation();
    }

    @Override
    public Long value4() {
        return getPopulation();
    }

    @Override
    public String value5() {
        return getCityFlag();
    }

    @Override
    public Long value6() {
        return getDistrictId();
    }

    @Override
    public String value7() {
        return getDeleteFlg();
    }

    @Override
    public CitiesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CitiesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CitiesRecord value3(String value) {
        setPronunciation(value);
        return this;
    }

    @Override
    public CitiesRecord value4(Long value) {
        setPopulation(value);
        return this;
    }

    @Override
    public CitiesRecord value5(String value) {
        setCityFlag(value);
        return this;
    }

    @Override
    public CitiesRecord value6(Long value) {
        setDistrictId(value);
        return this;
    }

    @Override
    public CitiesRecord value7(String value) {
        setDeleteFlg(value);
        return this;
    }

    @Override
    public CitiesRecord values(Long value1, String value2, String value3, Long value4, String value5, Long value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CitiesRecord
     */
    public CitiesRecord() {
        super(Cities.CITIES);
    }

    /**
     * Create a detached, initialised CitiesRecord
     */
    public CitiesRecord(Long id, String name, String pronunciation, Long population, String cityFlag, Long districtId, String deleteFlg) {
        super(Cities.CITIES);

        setId(id);
        setName(name);
        setPronunciation(pronunciation);
        setPopulation(population);
        setCityFlag(cityFlag);
        setDistrictId(districtId);
        setDeleteFlg(deleteFlg);
    }
}
