/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables.records;


import jp.co.toshiba.ppocph.jooq.tables.Districts;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistrictsRecord extends UpdatableRecordImpl<DistrictsRecord> implements Record6<Long, String, String, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.districts.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.districts.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.districts.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.districts.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.districts.chiho</code>. 地方
     */
    public void setChiho(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.districts.chiho</code>. 地方
     */
    public String getChiho() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.districts.district_flag</code>. 地域フラグ
     */
    public void setDistrictFlag(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.districts.district_flag</code>. 地域フラグ
     */
    public String getDistrictFlag() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.districts.shuto_id</code>. 州都ID
     */
    public void setShutoId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.districts.shuto_id</code>. 州都ID
     */
    public Long getShutoId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.districts.delete_flg</code>. 論理削除フラグ
     */
    public void setDeleteFlg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.districts.delete_flg</code>. 論理削除フラグ
     */
    public String getDeleteFlg() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Districts.DISTRICTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Districts.DISTRICTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Districts.DISTRICTS.CHIHO;
    }

    @Override
    public Field<String> field4() {
        return Districts.DISTRICTS.DISTRICT_FLAG;
    }

    @Override
    public Field<Long> field5() {
        return Districts.DISTRICTS.SHUTO_ID;
    }

    @Override
    public Field<String> field6() {
        return Districts.DISTRICTS.DELETE_FLG;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getChiho();
    }

    @Override
    public String component4() {
        return getDistrictFlag();
    }

    @Override
    public Long component5() {
        return getShutoId();
    }

    @Override
    public String component6() {
        return getDeleteFlg();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getChiho();
    }

    @Override
    public String value4() {
        return getDistrictFlag();
    }

    @Override
    public Long value5() {
        return getShutoId();
    }

    @Override
    public String value6() {
        return getDeleteFlg();
    }

    @Override
    public DistrictsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DistrictsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DistrictsRecord value3(String value) {
        setChiho(value);
        return this;
    }

    @Override
    public DistrictsRecord value4(String value) {
        setDistrictFlag(value);
        return this;
    }

    @Override
    public DistrictsRecord value5(Long value) {
        setShutoId(value);
        return this;
    }

    @Override
    public DistrictsRecord value6(String value) {
        setDeleteFlg(value);
        return this;
    }

    @Override
    public DistrictsRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistrictsRecord
     */
    public DistrictsRecord() {
        super(Districts.DISTRICTS);
    }

    /**
     * Create a detached, initialised DistrictsRecord
     */
    public DistrictsRecord(Long id, String name, String chiho, String districtFlag, Long shutoId, String deleteFlg) {
        super(Districts.DISTRICTS);

        setId(id);
        setName(name);
        setChiho(chiho);
        setDistrictFlag(districtFlag);
        setShutoId(shutoId);
        setDeleteFlg(deleteFlg);
    }
}
