/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables.records;


import jp.co.toshiba.ppocph.jooq.tables.EmployeeRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRoleRecord extends UpdatableRecordImpl<EmployeeRoleRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employee_role.employee_id</code>. 社員ID
     */
    public void setEmployeeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employee_role.employee_id</code>. 社員ID
     */
    public Long getEmployeeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.employee_role.role_id</code>. 役割ID
     */
    public void setRoleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employee_role.role_id</code>. 役割ID
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EmployeeRole.EMPLOYEE_ROLE.EMPLOYEE_ID;
    }

    @Override
    public Field<Long> field2() {
        return EmployeeRole.EMPLOYEE_ROLE.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getEmployeeId();
    }

    @Override
    public Long component2() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getEmployeeId();
    }

    @Override
    public Long value2() {
        return getRoleId();
    }

    @Override
    public EmployeeRoleRecord value1(Long value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public EmployeeRoleRecord value2(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public EmployeeRoleRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRoleRecord
     */
    public EmployeeRoleRecord() {
        super(EmployeeRole.EMPLOYEE_ROLE);
    }

    /**
     * Create a detached, initialised EmployeeRoleRecord
     */
    public EmployeeRoleRecord(Long employeeId, Long roleId) {
        super(EmployeeRole.EMPLOYEE_ROLE);

        setEmployeeId(employeeId);
        setRoleId(roleId);
    }
}
