/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables.records;


import jp.co.toshiba.ppocph.jooq.tables.Shutos;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * 州都ビュー
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShutosRecord extends TableRecordImpl<ShutosRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shutos.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shutos.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.shutos.shuto_name</code>.
     */
    public void setShutoName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shutos.shuto_name</code>.
     */
    public String getShutoName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shutos.pronunciation</code>.
     */
    public void setPronunciation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shutos.pronunciation</code>.
     */
    public String getPronunciation() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Shutos.SHUTOS.ID;
    }

    @Override
    public Field<String> field2() {
        return Shutos.SHUTOS.SHUTO_NAME;
    }

    @Override
    public Field<String> field3() {
        return Shutos.SHUTOS.PRONUNCIATION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getShutoName();
    }

    @Override
    public String component3() {
        return getPronunciation();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getShutoName();
    }

    @Override
    public String value3() {
        return getPronunciation();
    }

    @Override
    public ShutosRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ShutosRecord value2(String value) {
        setShutoName(value);
        return this;
    }

    @Override
    public ShutosRecord value3(String value) {
        setPronunciation(value);
        return this;
    }

    @Override
    public ShutosRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShutosRecord
     */
    public ShutosRecord() {
        super(Shutos.SHUTOS);
    }

    /**
     * Create a detached, initialised ShutosRecord
     */
    public ShutosRecord(Long id, String shutoName, String pronunciation) {
        super(Shutos.SHUTOS);

        setId(id);
        setShutoName(shutoName);
        setPronunciation(pronunciation);
    }
}
