/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq;


import java.util.Arrays;
import java.util.List;

import jp.co.toshiba.ppocph.jooq.tables.Authorities;
import jp.co.toshiba.ppocph.jooq.tables.Chihos;
import jp.co.toshiba.ppocph.jooq.tables.Cities;
import jp.co.toshiba.ppocph.jooq.tables.Districts;
import jp.co.toshiba.ppocph.jooq.tables.EmployeeRole;
import jp.co.toshiba.ppocph.jooq.tables.Employees;
import jp.co.toshiba.ppocph.jooq.tables.RoleAuth;
import jp.co.toshiba.ppocph.jooq.tables.Roles;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * 権限テーブル
     */
    public final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * 地方テーブル
     */
    public final Chihos CHIHOS = Chihos.CHIHOS;

    /**
     * 都市テーブル
     */
    public final Cities CITIES = Cities.CITIES;

    /**
     * 地域テーブル
     */
    public final Districts DISTRICTS = Districts.DISTRICTS;

    /**
     * 社員役割テーブル
     */
    public final EmployeeRole EMPLOYEE_ROLE = EmployeeRole.EMPLOYEE_ROLE;

    /**
     * 社員テーブル
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * 役割権限テーブル
     */
    public final RoleAuth ROLE_AUTH = RoleAuth.ROLE_AUTH;

    /**
     * 役割テーブル
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Authorities.AUTHORITIES,
            Chihos.CHIHOS,
            Cities.CITIES,
            Districts.DISTRICTS,
            EmployeeRole.EMPLOYEE_ROLE,
            Employees.EMPLOYEES,
            RoleAuth.ROLE_AUTH,
            Roles.ROLES);
    }
}
