/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq;


import jp.co.toshiba.ppocph.jooq.tables.Authorities;
import jp.co.toshiba.ppocph.jooq.tables.Chihos;
import jp.co.toshiba.ppocph.jooq.tables.Cities;
import jp.co.toshiba.ppocph.jooq.tables.Districts;
import jp.co.toshiba.ppocph.jooq.tables.EmployeeRole;
import jp.co.toshiba.ppocph.jooq.tables.Employees;
import jp.co.toshiba.ppocph.jooq.tables.RoleAuth;
import jp.co.toshiba.ppocph.jooq.tables.Roles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 権限テーブル
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * 地方テーブル
     */
    public static final Chihos CHIHOS = Chihos.CHIHOS;

    /**
     * 都市テーブル
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * 地域テーブル
     */
    public static final Districts DISTRICTS = Districts.DISTRICTS;

    /**
     * 社員役割テーブル
     */
    public static final EmployeeRole EMPLOYEE_ROLE = EmployeeRole.EMPLOYEE_ROLE;

    /**
     * 社員テーブル
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * 役割権限テーブル
     */
    public static final RoleAuth ROLE_AUTH = RoleAuth.ROLE_AUTH;

    /**
     * 役割テーブル
     */
    public static final Roles ROLES = Roles.ROLES;
}
