/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq;


import jp.co.toshiba.ppocph.jooq.tables.Authorities;
import jp.co.toshiba.ppocph.jooq.tables.Cities;
import jp.co.toshiba.ppocph.jooq.tables.Districts;
import jp.co.toshiba.ppocph.jooq.tables.EmployeeRole;
import jp.co.toshiba.ppocph.jooq.tables.Employees;
import jp.co.toshiba.ppocph.jooq.tables.RoleAuth;
import jp.co.toshiba.ppocph.jooq.tables.Roles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.authorities</code>.
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>public.cities</code>.
     */
    public static final Cities CITIES = Cities.CITIES;

    /**
     * The table <code>public.districts</code>.
     */
    public static final Districts DISTRICTS = Districts.DISTRICTS;

    /**
     * The table <code>public.employee_role</code>.
     */
    public static final EmployeeRole EMPLOYEE_ROLE = EmployeeRole.EMPLOYEE_ROLE;

    /**
     * The table <code>public.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>public.role_auth</code>.
     */
    public static final RoleAuth ROLE_AUTH = RoleAuth.ROLE_AUTH;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;
}
